services:
  db:
    image: mysql:8.0
    container_name: studyroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyroom_service_development
    command: ["mysqld"]
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ban_note_shared_network

volumes:
  mysql_data:

networks:
  ban_note_shared_network:
    external: true