version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: studyroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyroom_service_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: studyroom_app
    command: bash -c "ruby grpc_service/server.rb"
    working_dir: /studyroom_service
    volumes:
      - .:/studyroom_service
      - /studyroom_service/tmp
    ports:
      - "50053:50053"
    depends_on:
      - db
      - redis
      - kafka
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: de840449ba36702434883c58f5574809
      BUNDLE_DEPLOYMENT: 0
      GRPC_PORT: "50053"
      REMOTE_DB_HOST: "mysql-user-service.mysql.svc.cluster.local"
      REMOTE_DB_PORT: "3306"
      REMOTE_DB_NAME: "user_service_db"
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME_DEV: studyroom_service_development
      DB_NAME_TEST: studyroom_service_test
      DB_NAME_PROD: studyroom_service_production
      DB_USERNAME: root
      DB_PASSWORD: 1234
    restart: always

  redis:
    image: redis:7
    container_name: studyroom_redis
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: studyroom_zookeeper
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: studyroom_kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  mysql_data:
