services:
  db:
    image: mysql:8.0
    container_name: studyroom_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: studyroom_service_development
    command: ["mysqld"]
    ports:
      - "${DB_PORT:-3306}:3306"   # ← 외부 포트를 유동적으로
    volumes:
      - mysql_data:/var/lib/mysql
