# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_operating_hour/service.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'room_operating_hour/room_operating_hour_pb'


descriptor_data = "\n!room_operating_hour/service.proto\x12-bannote.studyroomservice.roomoperatinghour.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a-room_operating_hour/room_operating_hour.proto2\xd4\x02\n\x18RoomOperatingHourService\x12\xb2\x01\n\x15GetRoomOperatingHours\x12K.bannote.studyroomservice.roomoperatinghour.v1.GetRoomOperatingHoursRequest\x1aL.bannote.studyroomservice.roomoperatinghour.v1.GetRoomOperatingHoursResponse\x12\x82\x01\n\x18UpdateRoomOperatingHours\x12N.bannote.studyroomservice.roomoperatinghour.v1.UpdateRoomOperatingHoursRequest\x1a\x16.google.protobuf.EmptyB\x98\x02\n1com.bannote.studyroomservice.roomoperatinghour.v1B\x0cServiceProtoP\x01\xa2\x02\x03\x42SR\xaa\x02-Bannote.Studyroomservice.Roomoperatinghour.V1\xca\x02-Bannote\\Studyroomservice\\Roomoperatinghour\\V1\xe2\x02\x39\x42\x61nnote\\Studyroomservice\\Roomoperatinghour\\V1\\GPBMetadata\xea\x02\x30\x42\x61nnote::Studyroomservice::Roomoperatinghour::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Studyroomservice
    module Roomoperatinghour
      module V1
      end
    end
  end
end
