# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_operating_hour/service.proto for package 'Bannote.Studyroomservice.Roomoperatinghour.V1'

require 'grpc'
require 'room_operating_hour/service_pb'

module Bannote
  module Studyroomservice
    module Roomoperatinghour
      module V1
        module RoomOperatingHourService
          # ================================
          # RoomOperatingHour Service
          # ?붿씪蹂??댁쁺 ?쒓컙 ?꾩껜 議고쉶 + 由ъ뒪??湲곕컲 ?낅뜲?댄듃
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.roomoperatinghour.v1.RoomOperatingHourService'

            # ?꾩껜 議고쉶 (room_id 湲곗?)
            rpc :GetRoomOperatingHours, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHoursRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHoursResponse
            # 由ъ뒪??湲곕컲 ?꾩껜 ?낅뜲?댄듃
            rpc :UpdateRoomOperatingHours, ::Bannote::Studyroomservice::Roomoperatinghour::V1::UpdateRoomOperatingHoursRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
