# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_operating_hour/service.proto for package 'Bannote.Studyroomservice.Roomoperatinghour.V1'

require 'grpc'
require 'room_operating_hour/service_pb'

module Bannote
  module Studyroomservice
    module Roomoperatinghour
      module V1
        module RoomOperatingHourService
          # ================================
          # RoomOperatingHour Service
          # 요일별 운영 시간 전체 조회 + 리스트 기반 업데이트
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.roomoperatinghour.v1.RoomOperatingHourService'

            # 전체 조회 (room_id 기준)
            rpc :GetRoomOperatingHours, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHoursRequest, ::Bannote::Studyroomservice::Roomoperatinghour::V1::GetRoomOperatingHoursResponse
            # 리스트 기반 전체 업데이트
            rpc :UpdateRoomOperatingHours, ::Bannote::Studyroomservice::Roomoperatinghour::V1::UpdateRoomOperatingHoursRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
