# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room/service.proto for package 'Bannote.Studyroomservice.Room.V1'

require 'grpc'
require 'room/service_pb'

module Bannote
  module Studyroomservice
    module Room
      module V1
        module RoomService
          # ================================
          # Room Service
          # - ?ㅽ꽣?붾８ ?앹꽦, 議고쉶, ?섏젙, ??젣瑜??대떦?섎뒗 ?쒕퉬??
          # ================================
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.room.v1.RoomService'

            # ?ㅽ꽣?붾８ ?앹꽦
            rpc :CreateRoom, ::Bannote::Studyroomservice::Room::V1::CreateRoomRequest, ::Bannote::Studyroomservice::Room::V1::CreateRoomResponse
            # ?뱀젙 ?ㅽ꽣?붾８ 議고쉶
            rpc :GetRoom, ::Bannote::Studyroomservice::Room::V1::GetRoomRequest, ::Bannote::Studyroomservice::Room::V1::GetRoomResponse
            # ?ㅽ꽣?붾８ 紐⑸줉 議고쉶
            rpc :ListRooms, ::Bannote::Studyroomservice::Room::V1::ListRoomsRequest, ::Bannote::Studyroomservice::Room::V1::ListRoomsResponse
            # ?ㅽ꽣?붾８ ?뺣낫 ?낅뜲?댄듃
            rpc :UpdateRoom, ::Bannote::Studyroomservice::Room::V1::UpdateRoomRequest, ::Bannote::Studyroomservice::Room::V1::UpdateRoomResponse
            # ?ㅽ꽣?붾８ ??젣
            rpc :DeleteRoom, ::Bannote::Studyroomservice::Room::V1::DeleteRoomRequest, ::Bannote::Studyroomservice::Room::V1::DeleteRoomResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
