# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_exception/service.proto for package 'Bannote.Studyroomservice.Roomexception.V1'

require 'grpc'
require 'room_exception/service_pb'

module Bannote
  module Studyroomservice
    module Roomexception
      module V1
        module RoomExceptionService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.roomexception.v1.RoomExceptionService'

            # ?꾩껜 議고쉶 (room_id 湲곗?)
            rpc :GetRoomExceptions, ::Bannote::Studyroomservice::Roomexception::V1::GetRoomExceptionsRequest, ::Bannote::Studyroomservice::Roomexception::V1::GetRoomExceptionsResponse
            # 由ъ뒪??湲곕컲 ?꾩껜 ?낅뜲?댄듃
            rpc :UpdateRoomExceptions, ::Bannote::Studyroomservice::Roomexception::V1::UpdateRoomExceptionsRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
