# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_exception/service.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'room_exception/room_exception_pb'


descriptor_data = "\n\x1croom_exception/service.proto\x12)bannote.studyroomservice.roomexception.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a#room_exception/room_exception.proto2\xaf\x02\n\x14RoomExceptionService\x12\x9e\x01\n\x11GetRoomExceptions\x12\x43.bannote.studyroomservice.roomexception.v1.GetRoomExceptionsRequest\x1a\x44.bannote.studyroomservice.roomexception.v1.GetRoomExceptionsResponse\x12v\n\x14UpdateRoomExceptions\x12\x46.bannote.studyroomservice.roomexception.v1.UpdateRoomExceptionsRequest\x1a\x16.google.protobuf.EmptyB\x84\x02\n-com.bannote.studyroomservice.roomexception.v1B\x0cServiceProtoP\x01\xa2\x02\x03\x42SR\xaa\x02)Bannote.Studyroomservice.Roomexception.V1\xca\x02)Bannote\\Studyroomservice\\Roomexception\\V1\xe2\x02\x35\x42\x61nnote\\Studyroomservice\\Roomexception\\V1\\GPBMetadata\xea\x02,Bannote::Studyroomservice::Roomexception::V1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Bannote
  module Studyroomservice
    module Roomexception
      module V1
      end
    end
  end
end
