# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: room_exception/service.proto for package 'Bannote.Studyroomservice.Roomexception.V1'

require 'grpc'
require 'room_exception/service_pb'

module Bannote
  module Studyroomservice
    module Roomexception
      module V1
        module RoomExceptionService
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.roomexception.v1.RoomExceptionService'

            # 전체 조회 (room_id 기준)
            rpc :GetRoomExceptions, ::Bannote::Studyroomservice::Roomexception::V1::GetRoomExceptionsRequest, ::Bannote::Studyroomservice::Roomexception::V1::GetRoomExceptionsResponse
            # 리스트 기반 전체 업데이트
            rpc :UpdateRoomExceptions, ::Bannote::Studyroomservice::Roomexception::V1::UpdateRoomExceptionsRequest, ::Google::Protobuf::Empty
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
