# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: reservation/service.proto for package 'Bannote.Studyroomservice.Reservation.V1'

require 'grpc'
require 'reservation/service_pb'

module Bannote
  module Studyroomservice
    module Reservation
      module V1
        module ReservationService
          # ================================
          # Reservation Service
          # - ?ㅽ꽣?붾８ ?덉빟 ?앹꽦, 議고쉶, ?섏젙, ??젣瑜??대떦?섎뒗 ?쒕퉬??
          # ================================
          # Reservation ?쒕퉬???뺤쓽
          class Service

            include ::GRPC::GenericService

            self.marshal_class_method = :encode
            self.unmarshal_class_method = :decode
            self.service_name = 'bannote.studyroomservice.reservation.v1.ReservationService'

            # ?덉빟 ?앹꽦
            rpc :CreateReservation, ::Bannote::Studyroomservice::Reservation::V1::CreateReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::CreateReservationResponse
            # ?뱀젙 ?덉빟 議고쉶
            rpc :GetReservation, ::Bannote::Studyroomservice::Reservation::V1::GetReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::GetReservationResponse
            # ?덉빟 紐⑸줉 議고쉶
            rpc :ListReservations, ::Bannote::Studyroomservice::Reservation::V1::ListReservationsRequest, ::Bannote::Studyroomservice::Reservation::V1::ListReservationsResponse
            # ?덉빟 ?뺣낫 ?낅뜲?댄듃
            rpc :UpdateReservation, ::Bannote::Studyroomservice::Reservation::V1::UpdateReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::UpdateReservationResponse
            # ?덉빟 ??젣 (?뚰봽????젣)
            rpc :DeleteReservation, ::Bannote::Studyroomservice::Reservation::V1::DeleteReservationRequest, ::Bannote::Studyroomservice::Reservation::V1::DeleteReservationResponse
          end

          Stub = Service.rpc_stub_class
        end
      end
    end
  end
end
